apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-saga-orche
  namespace: kafka
  labels:
    app: order-saga-orche
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-saga-orche
  template:
    metadata:
      labels:
        app: order-saga-orche
    spec:
      containers:
        - name: order-saga-orche
          image: yklee2002/order-saga-orche:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.default.svc.cluster.local:3306/orderdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root1234
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: org.hibernate.dialect.MySQLDialect
---
apiVersion: v1
kind: Service
metadata:
  name: order-saga-orche-service
  namespace: kafka
  labels:
    app: order-saga-orche
spec:
  type: NodePort
  selector:
    app: order-saga-orche
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30300
